### ISSUE TITLE
Ansi.set_title not working.

### ISSUE THREAD

**Issue by Sasszem** [tartley/colorama#112]
It dosn't matterr how I try, using byte arrays, str.encode("utf-8") or by ctypes.c_char_p, I can't get ansi.set_title work on windows. 
If I try with a regular string, it finds the problem in file win32.py, in line 154, in SetConsoleTitle, at return _SetConsoleTitleW(title), the error is: `ctypes.ArgumentError: argument 1: <Class 'TypeError'>: Wrong type`
Else, when trying with bytes and so on, the error is at the `set_title` funcs, becouse it `can't convert bytes to str inplicitly`

**Comment by kirbyfan64** [comment]
Dup of #110?

**Comment by Sasszem** [comment]
Yeah, it fixed it, but please update the downloads!
