### ISSUE TITLE
Colorama not working in conjunction with PyFiglet

### ISSUE THREAD

**Issue by cocodevienne** [tartley/colorama#123]
Wy isn't this working when I run the command: "python termcolor.py  -m --draw hello"?
Source is here: http://pastebin.com/EGY0PBrT

**Comment by wiggin15** [comment]
It looks there is a bug in the script. The first "if" condition in line 23 is True so you're printing the text regularly, without using colorama colors.

**Comment by cocodevienne** [comment]
Ok, I fixed it, but when I run it on Windows, I get an ANSI code...

**Comment by cocodevienne** [comment]
@wiggin15
