### ISSUE TITLE
autoreset=True doesn't work for file output (Python 3.6.0, Ubuntu)

### ISSUE THREAD

**Issue by phreakmonkey** [tartley/colorama#126]
I'm not sure if this is a known/expected limitation of autoreset, but it seems to fail to provide the reset codes after each print() in the case of buffer/file output.   

Example:
```
>>> from io import StringIO
>>> from colorama import init, Fore
>>> init(autoreset=True)
>>> print(Fore.GREEN + "Green") ; print("Not Green")
```
Works as expected, yet:
```
>>> buf = StringIO()
>>> print(Fore.GREEN + "Green", file=buf) ; print("Not Green", file=buf)
>>> buf.seek(0)
0
>>> print(buf.read())
```
Both lines are green.

**Comment by wiggin15** [comment]
Hi. `colorama.init` wraps stdout and stderr. Your StringIO object doesn't get wrapped by colorama. What happens here is that you print ANSI codes into the file, and only then print the content along with the ANSI codes to stdout - at that point, colorama does its magic (this would work on Windows too) but the "autoreset" will happen only after both lines are printed. There is a workaround if you want to explicitly wrap your stream:

    buf = colorama.initialise.wrap_stream(buf, convert=None, strip=False, autoreset=True, wrap=True)

**Comment by phreakmonkey** [comment]
That makes perfect sense, actually.  Thanks for the tip!
