### ISSUE TITLE
incorrect `fileno` func in StreamWrapper 

### ISSUE THREAD

**Issue by wh1100717** [tartley/colorama#130]
https://github.com/tartley/colorama/blob/1e850687f50d2f01db8098f94903096129ccf554/colorama/ansitowin32.py#L24

function `fileno` missing `self` param

and why it just raise an OSError ?

I got error with Python 3.5/3.6 in Windows 10 and roll back to 0.3.6 to fix this issue...

**Comment by wiggin15** [comment]
The reason it raises OSError is because of this: https://github.com/tartley/colorama/issues/103
I took the def directly from the related Python issue: http://bugs.python.org/issue24402, it doesn't have `self` either. o_o
I'm not getting an error, though, when I use colorama on Windows. Where exactly does it affect you?

**Comment by wh1100717** [comment]
@wiggin15 

cuz `click` using os.stdout.fileno func

![image](https://cloud.githubusercontent.com/assets/1681360/25415706/e27ba316-2a6b-11e7-808d-98af8f75e683.png)

**Comment by wiggin15** [comment]
Hmmm.. This means that even if we fix the "self" problem, there will still be an exception there because the function will throw OSError.

**Comment by wh1100717** [comment]
@wiggin15 yup..... it will break click initialization...

**Comment by ericfrederich** [comment]
Came across this myself today too and and tracked it down to this.
Fresh install of Python 2.7.13, pip install colorama, pip install click

```bash
python -c "import colorama; import click; colorama.init(); click.echo('hi')"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\click\utils.py", line 217, in echo
    file = _default_text_stdout()
  File "C:\Python27\lib\site-packages\click\_compat.py", line 621, in func
    rv = wrapper_func()
  File "C:\Python27\lib\site-packages\click\_compat.py", line 201, in get_text_stdout
    rv = _get_windows_console_stream(sys.stdout, encoding, errors)
  File "C:\Python27\lib\site-packages\click\_winconsole.py", line 261, in _get_windows_console_stream
    func = _stream_factories.get(f.fileno())
TypeError: fileno() takes no arguments (1 given)
```

... and @wiggin15 is correct, even if you add the `self` parameter it will still break, you'll get the `OSError` instead.

**Comment by herks** [comment]
Also tracked this down to being a colorama issue by running raw_input in iPython on windows. 
0.3.7 works, but 0.3.8 fails.

```
62 self.input = raw_input("enter Input")

C:\Users\blah\project\venv\lib\site-packages\win_unicode_console\raw_input.pyc in raw_i
nput(prompt)

79 sys.stderr.flush()
80

---> 81 tty = STDIN.is_a_TTY() and STDOUT.is_a_TTY()

83 if RETURN_UNICODE:
C:\Users\blah\project\venv\lib\site-packages\win_unicode_console\streams.pyc in is_a_TT
Y(self)

54 try:

---> 55 fileno = get_fileno()

56 except io.UnsupportedOperation:

57 return False
TypeError: fileno() takes no arguments (1 given)
```

**Comment by wiggin15** [comment]
Alright. I'll revert the change, reopen the original issue and release a new version.

**Comment by wiggin15** [comment]
Please let me know if v0.3.9 fixes the issue.

**Comment by cupen** [comment]
@wiggin15 In my environment, follow code can reproduct this issue with colorama-0.3.8.
```
$ python2.7 -c "from colorama import init; init(autoreset=True); import sys; sys.stdout.fileno();"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: fileno() takes no arguments (1 given)
```
Then I upgrade it to colorama-0.3.9, it works fine.  Thanks.
