### ISSUE TITLE
Terminal detection?

### ISSUE THREAD

**Issue by arnuschky** [tartley/colorama#136]
Does colorama detect the terminals capabilities and suppresses colors accordingly?

I am using `structlog` from logging, which uses colorama in turn. When executing my script using `popen`, log colors are not displayed. I am not trying to understand whether it's colorama that's suppressing colors (and if yes, whether I can force it) or if popen eats the colors (nom nom).

**Comment by wiggin15** [comment]
colorama strips colors in case of stdout redirection (we check if stdout is a `tty`, and it isn't in the case of `popen`). You can force colorama to pass the color codes to the output by passing `strip=False` to `colorama.init`

**Comment by arnuschky** [comment]
Ok, thanks.
