### ISSUE TITLE
Bright background may produce undesired behavior on Windows

### ISSUE THREAD

**Issue by Delgan** [tartley/colorama#142]
Hello.

I know that `LIGHT_EX` colors are not part of the standard, but I noticed a strange behavior while using it so I prefer to report it.

```python
from colorama import Fore, Back, Style, init
init()
rst, lr, r, b = Style.RESET_ALL, Back.LIGHTRED_EX, Fore.RED, Fore.BLUE
msg = "{1}back-light-red{0} 0 {2}red{0} 0 {3}blue{0}".format(rst, lr, r, b)
print(msg)
```

This produces:

![1504351426-screenshot](https://user-images.githubusercontent.com/4193924/29995106-0a39444a-8fe2-11e7-962e-261412593cee.png)

As you can see, once a background light color has been used, it infects other colors.

The bug does not occur with the light colors in foreground, nor with normal colors in background.

The bug may be "reset" if a normal background color is used.

```python
from colorama import Fore, Back, Style, init
init()
rst, lr, br, b = Style.RESET_ALL, Back.LIGHTRED_EX, Back.RED, Fore.BLUE
msg = "{1}back-light-red{0} 0 {2}red{0} 0 {3}blue{0}".format(rst, lr, br, b)
print(msg)
```
![1504351934-screenshot](https://user-images.githubusercontent.com/4193924/29995163-3b281b66-8fe3-11e7-98eb-45c5a16a693f.png)

This is tested with the default terminal of Windows 10, on Python 3.6.2 and colorama 0.3.9.
Also, I tried with the Linux bash terminal of Windows 10 and it worked perfectly fine.

Is it a known bug (which could explain why light colors are not documented)? Do you know if this can be fixed or if it is because of the Windows terminal?

**Comment by wiggin15** [comment]
This looks like a bug, caused by not resetting `self._light` in `WinTerm.reset_all`. Thanks for reporting this. I hope I will have time to commit a fix soon.

**Comment by Delgan** [comment]
@wiggin15 Thanks to you for the quick fix. 👍
