### ISSUE TITLE
UnboundLocalError in winterm.erase_screen()

### ISSUE THREAD

**Issue by shin-** [tartley/colorama#147]
*Originally reported here: https://github.com/docker/compose/issues/5263*

Thank you for your work on `colorama`!

The way the code is set up at the moment, if the `mode` parameter is not in the expected [0-2] range, no value will be assigned to the `cells_to_erase` and `from_coord` variables and an `UnboundLocalError` will be raised.

While an invalid mode is certainly an error case, it would be helpful to have it raise a more explicit exception.

**Comment by wiggin15** [comment]
Thanks for reporting this! I committed a fix. Please let me know if it works.

**Comment by shin-** [comment]
Thanks @wiggin15 !

The original reporter just confirmed this solved the issue for them. Do you have any expectation as to when the next release of `colorama` will be? We'll probably pin it to the git commit for the time being.
