### ISSUE TITLE
Cant find, or absence of, official documentation

### ISSUE THREAD

**Issue by mental32** [tartley/colorama#151]
I like colorama, and I try to utilize it fully, Although this is difficult when I cant find documentation for it.
The Github repo points to the pypi link and says "docs" although when I visit the link I cannot find anything except for the Example usage samples, this and the "docs/" folder in the repo are virtually all I can see in place of documentation.

If I am mistaken and simply cannot find the documentation, Please could you comment the link here.
Thank you

**Comment by skyem123** [comment]
Well... to be honest... there isn't really much to document?
If you want to know how to use it past enabling it, look up ANSI terminal colour escape sequences, this implements that on Windows (while letting systems like Linux do their own handling for it).
