### ISSUE TITLE
colorama.init() is interfering with readline completer

### ISSUE THREAD

**Issue by angus-y** [tartley/colorama#154]
I am running windows 10 with python version of 2.7.13. I'm using colorama for colored output along with the readline module for tab completion in raw_input(). So far the tab completer works. But when I call ```colorama.init()```, tab completion no longer works. The function is somehow interfering with the readline completer. I know both modules make use of the ctypes module so  there may be a problem in their. Here is my code 
```
import readline
import colorama

colorama.init()

COMMANDS = ['help','exit','show']
def complete(text, state):
    for cmd in COMMANDS:
        if cmd.startswith(text):
            if not state:
                return cmd
            else:
                state -= 1
def main_handler_console():
    readline.parse_and_bind("tab: complete")
    readline.set_completer(complete)
    while True:
        test_input=raw_input(':')
        print test_input
main_handler_console()
```
This is the simplified version of the code, I managed to isolate it down to this section where the ```colorama.init()``` is interfering with the tab completer. Commenting out ```colorama.init()``` makes the completer work.

**Comment by wiggin15** [comment]
Hi. Thanks for reporting this. We are aware of this problem but don't have a fix - it appears to be an issue with Python itself that was fixed in Python 3. See issue #52.

**Comment by angus-y** [comment]
Is there a way to still make the code run without porting to python 3. I have some modules that I am using that need to use python 2

**Comment by bitbytes01** [comment]
hello,

I used the keyword argument with completer. But when I run the program, I do not get a list. Is this a new issues or am I missing something

Windows 10
Python 3.9




`
# snip from imports
from prompt_toolkit import prompt
from prompt_toolkit.completion import WordCompleter

# Just the functions
def get_roll(player_name, roll_names):
    print(f"Available Rolls: {', '.join(roll_names)}")
    # for index, r in enumerate(roll_names, start=1):
    #     print(f"{index}. {r}")

    text = input(f"{player_name}, what is your roll?  ")
    selected_index = int(text) - 1

    # give it a list of words
    word_comp = WordCompleter(roll_names)
    roll = prompt(f"{player_name}, what is your roll: ", completer=word_comp)

    if not roll or roll not in roll_names:
        print(f'Sorry {player_name}, {roll} is out of play!')
        return None

    return roll`
