### ISSUE TITLE
Strings that start with a newline does not reset properly

### ISSUE THREAD

**Issue by MatanRubin** [tartley/colorama#170]
Running on MacOS 10.13.4 with Python 3.6.5 and colorama 0.3.9.

I noticed that if the string I want to print with colorama starts with a `\n` - reset stops working.

For example, the following example prints fine (e.g. resets and the end of the word "hello")

    print(Fore.BLACK + Back.YELLOW + 'hello' + Style.RESET_ALL)

![good](https://user-images.githubusercontent.com/4488227/41338787-d1e55fc6-6efb-11e8-9c49-a5062b9f3fba.png)

However, adding a `\n` before "hello" causes the entire line to be with yellow background, as if RESET_ALL does not work.

    print(Fore.BLACK + Back.YELLOW + '\nhello' + Style.RESET_ALL)

![bad](https://user-images.githubusercontent.com/4488227/41338778-c9e6f50a-6efb-11e8-8ac3-09266cde90a6.png)

**Comment by wiggin15** [comment]
This doesn't look related to colorama specifically. It is the behavior of the terminal emulators interpreting the ASCII codes. This line will produce the same result:
`echo -e "\e[43m\nHello World\e[0m"`
Oddly enough, it seems like the terminals behave differently if there is a scroll buffer (i.e. you run this command at the bottom of the screen) - then this happens - and when there is no scroll buffer (i.e. you run the command in a new screen) - then this doesn't happen... This looks like the intended behavior for some reason, as it is shared across different types of terminals.
I'm afraid there is nothing I can do to fix this.

**Comment by MatanRubin** [comment]
Running this command on my machine just generates:

    \e[43m
    Hello World\e[0m

Did you test this on MacOS?
