### ISSUE TITLE
PR 164 causes hang when autoreset=True

### ISSUE THREAD

**Issue by bbayles** [tartley/colorama#196]
Updating to 0.4.0 caused an application I work on to stop working. Investigating, I found that getting rid of `autoreset=True` fixed the hanging problem, but I need the `autoreset` behavior.

Working through the changes since 0.3.9, I found that reverting a3eabd264365158f9d213a7b0a512c6955f0d281 fixes the problem. This the merge for PR #164.

I've not nailed down why this affects me - I'm not using PyCharm - but I expect you'll hear from others as this update proliferates. If I can pin it down I'll submit a PR.

**Comment by bbayles** [comment]
Update: more specifically, it's 2057f036f23a8113587f9cd7bf558594444a9caf that causes the hang. Keeping the PyCharm behavior from 3579cdec48d86cc8f588a3c8b5c990f1e0118c95 seems fine; it's the moving of the function to a method that causes the problem.

**Comment by wiggin15** [comment]
Fixed in #198.

**Comment by wiggin15** [comment]
Uploaded v0.4.1 to PyPI. Thanks.
