### ISSUE TITLE
Replace ANSI sequences with an empty-string on non-ttys

### ISSUE THREAD

**Issue by exhuma** [tartley/colorama#211]
Consider the following example code:

    from colorama import init, Fore, Style
    init()
    print('>%r<' % Fore.RED)

When running this in the terminal, I would expect the following:

    >'\x1b[31m'<

But when running though "cat" or "less" for example (`python example.py | cat`), I would expect the following:

    ><

Most of the time, you only want colors when running in a tty. Other cases, redirection and piping you don't really want this as  it messes up the output.

**Comment by exhuma** [comment]
I just noticed the following in the docs:

> **init(strip=None):**
>     Pass True or False to override whether ansi codes should be stripped from the output. **The default
>     behaviour is to strip if on Windows or if output is redirected (not a tty).**

But I still get the ANSI codes when redirecting (as per the code above). Could this be a regression?

**Comment by wiggin15** [comment]
Hi there. Printing the representation of the color code (with %r) means the output isn't the actual color code, so it will not be converted or stripped, or interpreted correctly as a color by terminals. The repr is a string that contains `["'", "\" "x", "1", ...]`, rather than the actual color code. To illustrate this, compare the value of the ANSI code with the value of its repr (%r):

```python
>>> colorama.Fore.RED[0]
'\x1b'
>>> repr(colorama.Fore.RED)[0]
"'"
```
Since the string using %r is not a color code, colorama will ignore it. It will also not color text, not in a tty or when redirected.
Try to use %s instead - it will color the character `<` with red when using a terminal, but will write `><` uncolored (and without color codes) when redirecting the output.
I hope this helps.

**Comment by exhuma** [comment]
Oooh.... right...  Makes perfect sense :smile: 

I forgot that colorama proxies the output and filters the sequences. Thanks for the quick reply.

**Comment by exhuma** [comment]
I will leave this closed for now but have a quick question (or rather, I am curious about your opinion):

I have a log formatter which contains color codes in the format-string. Until recently I was using `blessings` for the color codes, but replaced it with `colorama` for Windows support (Diffs are referenced in exhuma/gouge#3).

AFAIK, `blessings` works in the way the I expected `colorama` to work: It sets the variables to empty-strings when not on a tty. So writing something like `'{t.green}foobar{t.normal}'.format(Terminal())` is essentially a "no-op" when using `blessings`. If the messages are then used in a log-formatter.

I currently have the issue that I am running a script in `cron` which sends a mail if there is any output on stderr or stdout. When using `blessings` the escape codes were properly removed. When using `colorama`, the codes are no longer stripped and the mails become really messy.

As far as I can tell, this may be because logging creates a new "StreamHandler" for the root logger which does not get wrapped by `colorama`.

... although by wrapping the global `sys.sdout` and `sys.stderr` (as colorama does), it should still work nonetheless (unless the logging `StreamHandler` somehow circumvents these, which I doubt).

What is your opinion on this?

**Comment by wiggin15** [comment]
I took a look at your code. My guess is that `colorama.init()` is not called in time, during the basicConfig call. Calling `Simple.basicConfig` does not create an instance of `Simple` (as it is a classmethod), meaning that `Simple.__init__()`, which is where the call to `colorama.init` lies, is not called in time (or at all?). If you move the call to colorama.init to the top of the file it may work.
