### ISSUE TITLE
add install instruction

### ISSUE THREAD

**Issue by ghost** [tartley/colorama#220]
according to here:

https://pypi.org/project/colorama

install is like this:

~~~
pip install colorama
~~~

while this might seem obvious, i think it should be listed here as well:

https://github.com/tartley/colorama

**Comment by ThiefMaster** [comment]
Don't people who write python code usually know how to install a package? ;x

**Comment by MinchinWeb** [comment]
> Don't people who write python code usually know how to install a package? ;x

Not everything is available on PyPI, and it's not always obvious where to get the latest stable version of a project (PyPI? GitHub? which branch?)

**Comment by ArztKlein** [comment]
After checking https://github.com/tartley/colorama, the install instructions are currently there. Should this issue be closed?

**Comment by wiggin15** [comment]
Thanks for spotting. Looks like this was added in 3d74dce2. Closing.
