### ISSUE TITLE
LIGHTYELLOW_EX is not #FFFF00, its more like a beige color

### ISSUE THREAD

**Issue by Ahmed-Mokhles** [tartley/colorama#227]
i used to write programs with colorama in python 3.7 on my old windows 8.1 machine.

a few days ago i upgraded to a new windows 10 machine, and i installed latest python and latest colorama on it.

however, in all the programs that i wrote on my older machine, including new programs that i wrote on the new one, anything with "LIGHTYELLOW_EX" or "Style.BRIGHT + LIGHTYELLOW_EX" isnt the old bright yellow it used to be, but more of a beige-like color.

this also applies to backgrounds, not only foregrounds.

here is some sample code:

```
import colorama
colorama.init()

print(colorama.Fore.LIGHTYELLOW_EX + "yellow text" + colorama.Style.RESET_ALL) # prints beige text
print(colorama.Style.BRIGHT + colorama.Fore.YELLOW + "yellow text" + colorama.Style.RESET_ALL) # prints beige text too
print(colorama.Fore.YELLOW + "yellow text" + colorama.Style.RESET_ALL) # prints dark beige text
```

could it be a bug from the latest version of colorama? or is it windows 10? i havent tried the older colorama version on this new windows 10 machine.

any help or guidance is greatly appreciated.

**Comment by wiggin15** [comment]
Hi @Ahmed-Mokhles .
The actual RGB value of colors depends on the terminal. Most terminals let you customize the colors - technically, you can make "yellow" appear blue. You can change the color settings in your terminal (cmd/PowerShell) properties.
