### ISSUE TITLE
colorama==0.4.2 not having proper python_requires metadata breaks Python 3.4 envs

### ISSUE THREAD

**Issue by webknjaz** [tartley/colorama#244]
I've seen a few issues related to this release already but it seems there's one more point missing.

When you do `pip install colorama>0.3` (in my case, it's declared as a dependency) Pip will check which versions are supposed to work under Python 3.4, exclude 0.4.3 because it has properly declared `python-requires` and select 0.4.2 because it doesn't. This will only fail after Pip downloads the dist and aborts the whole `pip install` process (https://travis-ci.com/cherrypy/cheroot/jobs/270777308#L280).

I think this should be corrected. What can you do?

1) Just unpublish this version from PyPI.
2) Publish the dist once again with the same source as 0.4.2 inside but also having proper metadata. Use `0.4.2.post0` to make a post-release. `0.4.2.post0 > `0.4.2` so Pip will always prefer it. Problem solved.

P.S. Yes, I understand that Python 3.4 is EOL and will probably wipe it from my CIs soon but I still wanted to post this suggestion for the sake of correctness.

**Comment by wiggin15** [comment]
I am thinking about removing the `python-requires` constraint altogether.

**Comment by webknjaz** [comment]
@wiggin15 this is a very bad idea.

**Comment by wiggin15** [comment]
Can you please explain why? As far as I know, colorama should work on older Python versions. If there isn't a specific issue that breaks compatibility, I don't see why we should break it on purpose, even if we don't run the tests with those versions any more.

**Comment by webknjaz** [comment]
Because when you will break support and ship another broken version, the situation will be the same. You'll ship next release marked as >3.4 and everyone will be getting that previous broken version.

**Comment by webknjaz** [comment]
OTOH, it's quite easy to add GH Actions job to test 3.4 and this would be safer, of course. But I wouldn't mark non-tested versions as supported.

**Comment by aidistan** [comment]
Dropping any python version should be placed in a minor update at least. Or it will viloate semantic versionings and break dependencies.

**Comment by tartley** [comment]
Closing.

I think this can be closed, as I've "yanked" the broken PyPI 0.4.2 release. ("Yank" is their term for delete it except for people who request that version number explicitly)

So Python 3.4 should now get colorama 0.4.1.
