### ISSUE TITLE
Regular expression in AnsiToWin32 exhibits catastrophic backtracking

### ISSUE THREAD

**Issue by mschwager** [tartley/colorama#247]
Hi there! I've been working on a new Python static analysis tool called [Dlint](https://github.com/dlint-py/dlint). Most recently I've been working on a rule that searches for regular expression denial-of-service: [DUO138](https://github.com/dlint-py/dlint/blob/master/docs/linters/DUO138.md). When running this rule against your codebase I found a violation:

```
$ python -m flake8 --select=DUO138 colorama/
colorama/ansitowin32.py:71:19: DUO138 catastrophic "re" usage - denial-of-service possible
```

After further investigation, it appears the violation in `colorama/ansitowin32.py` is a true positive. If we dig in further:

```python
class AnsiToWin32(object):
    ...
    ANSI_OSC_RE = re.compile('\001?\033\\]((?:.|;)*?)(\x07)\002?')
```

The violation occurs due to `'\001?\033\\]((?:.|;)*?)(\x07)\002?'`. In particular, this portion of the expression: `(?:.|;)*`. This is due to [mutually inclusive alternation](https://www.regular-expressions.info/redos.html) within a quantifier. Since `.` and `;` have character overlap. We can confirm the bug with a specially crafted string and the following code:

```python
from colorama import ansitowin32
ansitowin32.AnsiToWin32.ANSI_OSC_RE.match('\033]' + ';' * 64 + '\x08')
...Spins...
```

To fix the issue we should avoid the character overlap between `.` and `;`. One way to accomplish this is with the following expression:

```python
ANSI_OSC_RE = re.compile('\001?\033\\]((?:[^;]|;)*?)(\x07)\002?')
```

Hope this is helpful, let me know if you have any questions!

**Comment by wiggin15** [comment]
Thanks for reporting this!
What is the difference between `(?:.|;)` and `.`? (also between `(?:[^;]|;)` and `.`)?

**Comment by mschwager** [comment]
They should all be the same! I believe `(?:.|;)`, `(?:[^;]|;)`, and `.` are the same - I was just aiming for the most minimally invasive change :)

Although, if you're going to use `.`, I would recommend using something like `[^\x07]` to account for the next portion of the expression.

**Comment by wiggin15** [comment]
Thank you.
Since we're using `*?` (lazy), the expression will stop as soon as it finds `\x07` anyway so I _think_ `[^\x07]*?` will not improve too much over `.*?`. However, maybe a better expression is `[^\x07]*` (greedy): if I am not mistaken, this will let the engine consume the non-\x07 characters faster (instead of stopping after each character and checking if \x07 is next) so I _think_ it's more optimal, especially if \x07 isn't even there (?).

**Comment by wiggin15** [comment]
The reason the semicolon was there is that we expect to have one (and only one) as part of the sequence. We never really checked for it properly, so malformed commands like `\033]0\x07` could crash colorama :(

**Comment by mschwager** [comment]
Yup, a common, non-catastrophic pattern I see is `([^\x07]*)(\x07)`. The ReDoS page previously mentioned even calls this out under [Qualifiers in Sequence](https://www.regular-expressions.info/redos.html). That sounds like a good solution to me :+1:

**Comment by wiggin15** [comment]
Thanks! I will commit a change over the weekend (need to test it a little). One more change I want to make is use `\a` instead of `\x07` for the BEL character. Looks more friendly :)
