### ISSUE TITLE
Colorama not working with input(...)

### ISSUE THREAD

**Issue by ghost** [tartley/colorama#252]
System: Windows 10
Shell: cmd.exe
Python: 3.8.1
Colorama: 0.4.3

For example:

from colorama import Fore, init
init()
input(Fore.RED + "test")
This prints ←[31mtest instead of of "test" in red.

The weird thing is, it does work in the VSC terminal. Tried looking for solutions could not find any working

**Comment by wiggin15** [comment]
Please have a look at #103

**Comment by wiggin15** [comment]
Duplicate of #103
