### ISSUE TITLE
init autoreset=True breaks colors in terminal output

### ISSUE THREAD

**Issue by Serfentum** [tartley/colorama#258]
Hi! I'm really sorry, can't understand why my shell works in such way, but when I write code like this
```python
import colorama
from colorama import Fore


colorama.init(autoreset=True)
print(Fore.Green, 'Some text', sep='')
```

And run it in my terminal there is no colors at all( 
If I don't set autoreset to True and reset style manually (via Fore.RESET) it works fine except burden of manual style resetting. What's wrong with my approach?
In pycharm code with `colorama.init(autoreset=True, convert=False, strip=False)` works ok - it outputs colored text

I have ubuntu 16.04 and GNOME Terminal 3.18.3, thank you very much!

**Comment by wiggin15** [comment]
Hi. This indeed looks odd, but apparently expected, as "autoreset" resets the colors after each `print` argument. In your case, the code prints to the terminal:
Green (reset), 'Some text' (reset)
and this is why "Some text" is printed without the green color. Try using:

```python
print(Fore.GREEN + 'Some text', sep='')
```

**Comment by Serfentum** [comment]
Thank you very much, I missed it!
