### ISSUE TITLE
Make it possible for more than just @tartley to make a new PyPI release

### ISSUE THREAD

**Issue by tartley** [tartley/colorama#26]
I'm not sure whether anyone else is able to make a colorama release to PyPI without my personal PyPI credentials. Is this a problem? Should we fix it?

**Comment by tartley** [comment]
Yep, absolutely. What's your pypi username?

**Comment by wiggin15** [comment]
It's wiggin15 like here, but looks like you already figured this out :) thanks.

**Comment by tartley** [comment]
I'm sure this isn't helpful, but just in case: There are targets in the Makefile to remind me of the commands used to upload versions to PyPI. The Makefile only exists to remind me of a few commonly used commands.
