### ISSUE TITLE
why no tar.gz/source distributable for 0.4.4 ?

### ISSUE THREAD

**Issue by SomberNight** [tartley/colorama#284]
Previous releases, such as 0.4.3 had both a wheel and a tar.gz/zip source distributable.
0.4.4 only has a wheel uploaded to PyPI.

Compare:
https://pypi.org/project/colorama/0.4.3/#files
https://pypi.org/project/colorama/0.4.4/#files

This breaks `pip install --no-binary :all:`, e.g. as used here:
https://github.com/spesmilo/electrum/blob/9bc4182924424bab2b1c11ef1e9c7f32ab6f2922/contrib/make_packages#L9-L10

**Comment by tartley** [comment]
Thanks for reporting. I'll fix it today, and add this to the new 'releases checklist', so we can be more reliable about stuff like this.

**Comment by tartley** [comment]
I've been automating the release process recently, to try and make it more reliable, and I had a bug in the new release scripts, that omitted the source distributions from the upload. Fixed now: https://github.com/tartley/colorama/commit/e0a314e302cd55dc4c78462965b6ef90dd3c74c8

And I manually uploaded the 0.4.4 sdist. Should be working now.
