### ISSUE TITLE
Hardcoded ANSI sequences in logging don't get converted

### ISSUE THREAD

**Issue by jalaj-k** [tartley/colorama#287]
I am having an [app](github.com/codegods/blogit), a component of which adds some colors to its logs. And it depends upon colorama for cross-platform support. But I am getting weird outputs in the console. You may see it for yourself:

Expected output:
![Annotation 2020-10-22 150417](https://user-images.githubusercontent.com/67556827/96853396-ed4f6800-1477-11eb-8a35-78f55dc57022.jpg)

Actual output:
![Annotation 2020-10-22 150428](https://user-images.githubusercontent.com/67556827/96853404-efb1c200-1477-11eb-8f22-7493bf91627a.jpg)

<details>
<summary>Relevant files</summary>

- https://github.com/codegods/blogit/blob/master/helpers/formatter.py
- https://github.com/codegods/blogit/blob/master/helpers/config_loader.py
- https://github.com/codegods/blogit/blob/master/scripts/start.py

</details>

Also: codegods/blogit#9

Why is it that only half the sequences actually get converted?

**Comment by jalaj-k** [comment]
@tartley @wiggin15 Any  updates on this one? We need this for our project as all the school PCs run Windows while our development machines don't.

**Comment by tartley** [comment]
Hi. complete speculation, but I wonder if this is related to this:

In the README section [Recognized ANSI sequences](https://github.com/tartley/colorama/#recognised-ansi-sequences), right at the end, is a line that says:

Any other form of ANSI sequence, such as single-character codes or alternative initial characters, are not recognised or stripped. It would be cool to add them though. Let me know if it would be useful for you, via the Issues on GitHub.

I have long wondered why nobody has ever complained about these being supported. Could it be this is the cause of your problem?

**Comment by tartley** [comment]
Aha, I see from your linked issue that you switched to using ansicon instead of colorama. Great, glad you found a fix.

**Comment by jalaj-k** [comment]
> Could it be this is the cause of your problem?

I don't suppose so, because if you see the screenshots then only the first few lines are uncoloured while others are just perfect and all the ANSI codes are being added by the same file, so this must be something else.

**Comment by tartley** [comment]
Ah, fair enough. Thanks for that info.
