### ISSUE TITLE
input() with color will crash line

### ISSUE THREAD

**Issue by u23a** [tartley/colorama#288]
I want to color the prompt text using following code:
`input(Fore.GREEN+'some prompt'+Style.RESET_ALL)`
but this will crash the line like this:
![2020-10-25-120731_971x51_scrot](https://user-images.githubusercontent.com/27770920/97098676-b2894200-16ba-11eb-995e-abc5bee21321.png)

The "aaaaaaaaaa....." strings don't reach the end of the line and override start of this line.

I can't figure out this issue, can anyone help?

**Comment by u23a** [comment]
@tartley @wiggin15 Can you help me? Thanks.

**Comment by wiggin15** [comment]
Hi @u23a . The problem doesn't reproduce when running just the line you mentioned, so maybe some other part of your program is causing it.

Can you please share or link to the entire code that reproduces this?
Also, which operating system are you running on, and what Python version are you using?

**Comment by u23a** [comment]
I just run it in python interactive mode. It's  so odd.
The entire code is just following:
```
from colorama import Fore,Style
input(Fore.GREEN+'some prompt'+Style.RESET_ALL)
```
```
Environment:
OS: Archlinux
Shell: zsh 5.8
Python: 3.7.5 & 3.8.6 (pyenv management)
```
I also run it in a VirtualBox VM(Kali Linux), and it has the same issue.
If you need more info, please tell me.

**Comment by wiggin15** [comment]
I run on the following environment:
```
OS: macOS 10.15 Catalina
Shell: zsh 5.8
Python: 3.7.3 & 3.9
Terminal: iTerm2
```
I also tried on Ubuntu 18.04 with Python 3.6.9.
I admit I never tried Archlinux and Kali Linux, but I can't think of a reason why it would be different on these distros.
I don't know how to debug this. Is there any chance you have some modification in the colorama code?

**Comment by u23a** [comment]
I didn't modify colorama code.
I tried in Windows and WSL Ubuntu:
```
Windows 10 with Python 3.8.6: Ok
WSL Ubuntu 18.04.2 with Python 3.6.9: Fail
```
It's confusing. Let's just forget this issue.

**Comment by Delgan** [comment]
Out of curiosity, I tested your snippet... Same issue on my computer actually!

```
OS: Arch Linux
Shell: bash 5.0.18
Terminal: termite
Python: 3.8.6
Colorama: 0.4.4 
```

**Comment by u23a** [comment]
@Delgan Thanks for reproducing it.

Just no ideas how to debug it.

**Comment by Delgan** [comment]
In any case it's not caused by `colorama`. It's more likely a shell thing (maybe related to PS1 prompt?). Or perhaps an issue inside the `InteractiveConsole` implementation of Python.

```bash
python -ic 'input("Some string...\x1b[0m")'
```

```bash
python -ic 'input("\x1b[31mSome string...")'
```
The following command also generates weird overriding at some point on my computer:

```bash
echo -en "Some string...\x1b[0m"
```

It seems the same issue has been reported in #143.

It's probably worth asking for more information to a specialized community such as [Unix & Linux](https://unix.stackexchange.com/) or [Super User](https://superuser.com/) Stack Exchange.

**Comment by wiggin15** [comment]
This might be related:
https://bugs.python.org/issue17337

**Comment by Delgan** [comment]
Yeah, it definitely looks like the same problem. :+1:

**Comment by u23a** [comment]
Thx for helping me find the reason.
I'll close this issue.
