### ISSUE TITLE
Some colors and styles are not working properly on Windows 10 with Python 3.9.1

### ISSUE THREAD

**Issue by Aguileitus** [tartley/colorama#296]
Look at demos 1 and 2.
In demo01, the black and white backgrounds in the first column (the names) are inverted(?) (and black background is not exactly black) and in the last column (white) the last mode (bright) looks also inverted. Also, notice that all the background colors in the first column are slightly different from the rest.

In demo02, the last print (styles) is changing the background for some reason.

And I think demos 3 and 4 are also not working correctly. 

![image](https://user-images.githubusercontent.com/14335637/104084715-285b6f00-520f-11eb-8cad-8a2eecf8fba9.png)

**Comment by wiggin15** [comment]
Hello!
I'm afraid I can't reproduce this behavior. The colors are correct on my setup - Windows 10 1909, Python 3.9.1. This Windows version may be a little old so that may be the difference, but I don't have access to a newer one. Can anyone else try to reproduce?
Is it possible your terminal properties are not set to the default? Can you try to run on a different machine?

**Comment by Sanjay-Swain** [comment]
Hello
I guess it is you have some custom color scheme enabled for command prompt. That may mess up with output colors. 
For example here is the screenshot from default command prompt:
![ColorScheme](https://user-images.githubusercontent.com/59828852/106140728-25f88f00-6195-11eb-94bd-7c0e01843a06.png)

And here is the screenshot by running the same program on windows terminal (with a custom color scheme): 
![ColorScheme2](https://user-images.githubusercontent.com/59828852/106140832-4b859880-6195-11eb-87c4-28b3855c9791.png)

As you can see the colors are different on the same machine. So you may want to check your command prompt settings, you can get there by right clicking on the menu bar of command prompt and selecting properties.

If this is not the case then you can try powershell, default one should work (the one that comes pre-installed, it's outdated but it works for me).

**Comment by Aguileitus** [comment]
Hi,

It looks like I accidentally changed some of color that are under "Colors" tab in in the properties, after changing them back (comparing with another machine) the demos now show the correct colors

![image](https://user-images.githubusercontent.com/14335637/108436147-86b53d80-7210-11eb-890d-89b7654c2352.png)

Thanks @wiggin15 @Sanjay-Swain !
