### ISSUE TITLE
Color Not Outputting

### ISSUE THREAD

**Issue by AlphaMirage** [tartley/colorama#297]
### I don't get any color but instead something weird...

My Code:

```python
from colorama import Fore, Back, Style
print(Fore.RED + 'some red text')
print(Back.GREEN + 'and with a green background')
print(Style.DIM + 'and in dim text')
print(Style.RESET_ALL)
print('back to normal now')
```

My output:
```
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
============== RESTART: C:\Users\talin\Desktop\Code\color-test.py ==============
[31msome red text
[42mand with a green background
[2mand in dim text
[0m
back to normal now
>>> 
```

And just-in-case the output looks weird:

![image](https://user-images.githubusercontent.com/77280625/105109599-d6c2a800-5a8a-11eb-974e-597b3518116f.png)

What is wrong?

I don't have any errors so `colorama` is installed right...

**Comment by ownaginatious** [comment]
I believe you need to do this on Windows to make the colors work:

```python
from colorama import init

init()
```

**Comment by AlphaMirage** [comment]
> I believe you need to do this on Windows to make the colors work:
> 
> ```python
> from colorama import init
> 
> init()
> ```

Yes, I tried that and it didn't work... Then I copied & pasted your code and it did! I guess I was typing it wrong before!
