### ISSUE TITLE
Vs code doesn't recognize the colorama

### ISSUE THREAD

**Issue by CristinoCg** [tartley/colorama#301]
I tried to use the colorama in vs code and it doesn't work

**Comment by mylesbartlett72** [comment]
Stack trace/screenshots as appropriate, please.

**Comment by rausb** [comment]
I think I'm having the same problems that OP has.

During debugging in Visual Studio 2019 with Python 3.9 64 Bit colors simply won't show in the terminal: the printout stays white. But if I open the same script manually in cmd, colorama shows its colors.

If I can give you any further info, I'm happy to deliver.

**Comment by manjunathmayya** [comment]
I tried running in VS code. I observed below things.
1.  Normal black and white output seen in OUTPUT window.
2.  But if I run the script on the TERMINAL of VS Code, I see colored output.

As a developer and user I think this behavior is acceptable. Attached screen shots from VS code OUTPUT and TERMINAL windows here. Hope it helps.

![image](https://user-images.githubusercontent.com/41788269/118649152-ce903480-b800-11eb-8687-c489dcb40c12.png)
![image](https://user-images.githubusercontent.com/41788269/118649184-d8b23300-b800-11eb-9510-2f9db8e9606c.png)

**Comment by mylesbartlett72** [comment]
Are you on Windows or Unix/Linux?  AFAIK Colorama works on the VS Code terminal on Linux (from my experience).

**Comment by CristinoCg** [comment]
> I tried to use the colorama in vs code and it doesn't work

**Comment by CristinoCg** [comment]
> Stack trace/screenshots as appropriate, please.
> I could probably tell you what's wrong as a user of colorama, but can't without any info apart from "it doesnt work". Please, to everyone reading this, STOP CREATING ISSUES LIKE THIS! It is just an annoyance for developers, and nobody knows what the problem is. I see too many of these types of issues on GitHub, it is very annoying, especially those that appear on your own projects!

Sorry, i was a really begginer when i made this comment 
I'll be trying to see it again, I'm not using it for a long time 
So i need to go there and check it again

**Comment by nfrancque** [comment]
Can this be reopened?  Using git bash in Windows colorama works always, but using the same install of git bash as a terminal inside of vscode I always see the ANSI codes and not colors.  Other things (presumably not colorama-based) have colors inside the terminal.  Running the same thing in Ubuntu in a bash shell inside vscode, colorama works.  Using windows cmd as the shell inside vscode on the same windows machine also works.  So it seems to be git bash/msys specific.

Issue here for vscode says they don't intend to touch it https://github.com/microsoft/vscode/issues/103742.

Is there a way to determine whether this is colorama or something else?
