### ISSUE TITLE
Style.DIM doesn't work on Windows

### ISSUE THREAD

**Issue by llamafilm** [tartley/colorama#305]
Is this a known issue?  It works on macOS, but on Windows `Style.DIM` looks the same as regular text.  I tried both Command Prompt and Powershell.  Example program:

```py
from colorama import init, Fore, Back, Style

init(autoreset=True)

print(Fore.RED + 'some red text')
print(Back.GREEN + 'and with a green background')
print(Style.DIM + 'and in dim text')
print(Style.BRIGHT + 'this is bright')
print(Style.RESET_ALL)
print('back to normal now')
```

<img width="226" alt="powershell" src="https://user-images.githubusercontent.com/3991046/118905514-b4be2280-b8d0-11eb-9025-e2debb87fae8.png">
<img width="251" alt="cmd" src="https://user-images.githubusercontent.com/3991046/118905515-b5ef4f80-b8d0-11eb-8e92-639c4b8a1269.png">

**Comment by joeypencil** [comment]
Please read the `README.md`; it is expected that the Dim styles won't work in Windows.

**Comment by llamafilm** [comment]
Thanks, I hadn’t seen that part
