### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by msabramo** [tartley/colorama#31]
There is already a .travis.yml but there are no travis builds yet

**Comment by wiggin15** [comment]
Looks like I don't have permissions to edit the settings for this project. @tartley will have to enable this.

**Comment by tartley** [comment]
The travis builds (and build badge in the README) are working now.

What do I need to do to give @wiggin15 permissions to tweak these settings? As far as I can tell, the travis settings are available to the owner of the git repo, and wiggin15 is a collaborator. So I would have expected it to work. Is there a distinction between 'owner' and 'collaborator' that I don't know about?

**Comment by msabramo** [comment]
Not sure. Probably an owner can change repo settings and a collaborator can't. 

But now that you've turned on Travis CI, there's not much to tweak in the Travis or GitHub UIs. 

Pretty much everything about Travis is tweaked by making changes to `.travis.yml`.
