### ISSUE TITLE
Colorama does not work with the logging module on Windows

### ISSUE THREAD

**Issue by mara004** [tartley/colorama#316]
I am using colorama for coloured terminal output on Windows with custom ANSI escape sequences in a medium size library that I currently develop. I noticed that this works well for regular prints, but not for logging output. While prints are coloured correctly, log messages still display the raw escape sequences on Windows.
Is this a known issue? Can it be mitigated with special configuration?

**Comment by tartley** [comment]
If the process that is printing the log content to the console has imported colorama, then this should work. But if you are using regular Windows command-line tools such as 'type' to display the content of the log file, then Colorama is unable to make this work, sorry.
