### ISSUE TITLE
[BUG] Unicode encode error with Gitbash

### ISSUE THREAD

**Issue by VinceCabs** [tartley/colorama#319]
Hi,

I came accross a strange behaviour when using colorama with in Gitbash.

Here is a test file :

```python
import colorama

print("\N{Heavy Check Mark} check mark")
```

Standard run is OK : 

```sh
$ python test_colorama.py
✔ check mark
```

But `stderr` is not empty (we get an error) when printing into a file : 

```sh
$ python test_colorama.py > output.txt
Traceback (most recent call last):
  File "test_colorama.py", line 3, in <module>
    print("\N{Heavy Check Mark} check mark")
  File "C:\[...]\.venv\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2714' in position 0: character maps to <undefined> 
```

**Comment by tartley** [comment]
I think the conclusion here is that this is not a colorama bug, so I'm closing. Please shout if you think I'm wrong. Thank you!

**Comment by prusswan** [comment]
Related: https://github.com/python/cpython/issues/86873

This is happening for conda-tree which prints outs a tree using '\u251c' or (“├” in Unicode)

Even if this is correct behavior with sysout redirection on Windows, we still need a 'correct' place to set the encoding to utf8 (seems to be using `PYTHONIOENCODING=utf-8` for now)
