### ISSUE TITLE
Light mode vs. Dark mode

### ISSUE THREAD

**Issue by renejsum** [tartley/colorama#329]
I am using colorama with python logging and in light mode terminals the text is almost impossible to read. structlog uses BRIGHT for text. I could ask structlog to change that, but it occured to me that it might be better with a light/dark mode option for colorama?

Have anyone considered adding light/dark mode to colorama?

**Comment by tartley** [comment]
It's a creative idea, but my motivation for it is low. Colorama is in maintenance mode, because of a shortage of people who contribute time and effort to maintain it, so I'm avoiding any new features which might increase the maintenance burden.
