### ISSUE TITLE
Support setting the console title

### ISSUE THREAD

**Issue by tartley** [tartley/colorama#34]
Migrated from https://code.google.com/p/colorama/issues/detail?id=13
Reported by rogerbinns, May 19, 2010

SetConsoleTitle
http://msdn.microsoft.com/en-us/library/ms686050%28VS.85%29.aspx

Perhaps an optional parameter to init to set it, and automatically restore
on program exit that works on both xterm and Windows.

You can also intercept the escape sequences to set it:

  http://tldp.org/HOWTO/Xterm-Title-3.html

**Comment by tartley** [comment]
closing as per wiggin's comment on https://github.com/tartley/colorama/issues/25

**Comment by mixmastamyk** [comment]
Any reason for closing this?  It would be a nice-to-have, no?
