### ISSUE TITLE
The library itself is not working properly

### ISSUE THREAD

**Issue by bebra284** [tartley/colorama#342]
As a novice programmer, I decided to get acquainted with the libraries and decided to start with colorama.
The problem is that it doesn’t give me an error, but how would the command in python be perceived but not reproduced correctly
Here are the screenshots:
![Скриншот 26-04-2022 215508](https://user-images.githubusercontent.com/95929263/165342021-aa38c8c1-c27c-4883-91c9-79ea709248d1.jpg)
![Скриншот 26-04-2022 215448](https://user-images.githubusercontent.com/95929263/165342026-b65acd5e-9583-4db0-91c8-5c526628b9e1.jpg)
The code itself works correctly, but the library produces strange characters

Please help who knows and understands

**Comment by bebra284** [comment]
Everything, the issue is resolved, I figured out what the problem is

**Comment by ceyhunveyselism** [comment]
BUT WHAT WAS THE PROBLEM MY GUY??????
