### ISSUE TITLE
Is 0.4.5 released or not?

### ISSUE THREAD

**Issue by torarvid** [tartley/colorama#347]
Hi there 👋🏻 Just got a PR from dependabot to update colorama from 0.4.4 to 0.4.5. But then I saw in the release notes that 0.4.5 is marked as `In progress, unreleased`, so just wanted to check if either the Changelog is just not up-to-date, or perhaps 0.4.5 got released pre-maturely by mistake.

Thanks!

**Comment by wiggin15** [comment]
Hi.
Yes, version 0.4.5 is released.
The changelog is not up-to-date - this is an oversight. I will fix it. Thanks for letting us know.
