### ISSUE TITLE
Support NO_COLOR

### ISSUE THREAD

**Issue by hansfn** [tartley/colorama#382]
See https://no-color.org/

I think it makes sense if this library supports NO_COLOR instead of all applications using the library implements support. (Sorry if it is already included.)

**Comment by Delgan** [comment]
See https://github.com/tartley/colorama/issues/268

**Comment by hansfn** [comment]
So sorry for the noise. I did search, but on the main search result area it said no results. That was for code only. It was clear in the left menu that there is already an issue - my bad.
