### ISSUE TITLE
Windows use case?

### ISSUE THREAD

**Issue by JPHutchins** [tartley/colorama#387]
Since Windows Terminal supports ANSI escapes, I am curious if colorama disables itself in use cases where it is redundant?  Like it would for Linux, for example.

What exactly are the terminals on Windows that still require colorama?

I want to make sure that my packages have good compatibility but I'm not thrilled to support *every* ancient Windows console!

Thanks,
JP

**Comment by njsmith** [comment]
Does this section of the docs answer your question clearly? If not can you
suggest edits that would make it clearer?

https://github.com/tartley/colorama?tab=readme-ov-file#initialisation

**Comment by JPHutchins** [comment]
Yes, thank you!  It seems that in most cases the code will follow the path eventually to `enable_vt_processing`:

https://github.com/tartley/colorama/blob/136808718af8b9583cb2eed1756ed6972eda4975/colorama/winterm.py#L178-L195

This calls the Windows API defined here: https://learn.microsoft.com/en-us/windows/console/setconsolemode

In the vast majority of (modern) cases this is basically a no op because the terminal already has the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag set and colorama will not impact expected ANSI processing.
