### ISSUE TITLE
play nicely with other stdout/stderr wrappers

### ISSUE THREAD

**Issue by tartley** [tartley/colorama#39]
Migrated from https://code.google.com/p/colorama/issues/detail?id=41
Reported by eallik, Jan 21, 2013

Take a look at the wrapper provided at http://stackoverflow.com/a/3259271/247623 --it reliably enables Unicode output on cmd.exe; unquestionably useful. However, it turns out that colorama does not work out of the box in combination with that wrapper.

The reasons for this are:
* first of all, colorama needs to be activated after that wrapper because the other wrapper is more low level/fundamental
* colorama remembers the `orig_stdout` and `orig_stderr` references in its `initialise.py` at import time, thus, by the time `init()` is called, any wrappings that have taken place before `import colorama` and `init()` are effectively cancelled/ignored
* colorama does not convert ANSI codes for streams who are not `.isatty() == True`; I'm not sure why such check was implemented in the first place, but it looks to me that colorama works perfectly well with streams that do not have such property.

The current workaround is to manually update `orig_stdout` and `orig_stderr` with fresh values from `sys.stdout` and `sys.stderr` respectively, and also do `sys.stdout.isatty = sys.stderr.isatty = lambda: True` to satisfy the `is_a_tty` check in `ansitowin32.py`. However, it would be nice if colorama did not require such workaround to compose nicely with other wrappers.

**Comment by tartley** [comment]
from Jonathan@rangespan.com
Thanks for the report.

The reason I added the 'isatty()' check is that I thought this was the correct way to behave if, for example, the output is going to somewhere other than a terminal, e.g. is running as a GUI process without a terminal, or stdout is piped to a file. Calling the Windows console functions doesn't seem necessary in these cases, can't possibly work, and I was afraid might even raise errors in some situations.

**Comment by tartley** [comment]
from eallik

The purpose of isatty you've described is obviously completely valid, and it's thus hard to argue against having measures in colorama for proper dealing with redirected standard streams. However, thinking of it from a different angle, perhaps the interface to activating colorama should be slightly different to start with. Currently it's implemented as some sort of a "compilation flag" in the "header" of the program, figuratively speaking, which means it has to be (a bit) overly smart about its behavior and take decisions based on what it can tell about the environment it's running in. If we were to approach this from a somewhat more functional programming point of view, perhaps the side effects introduced by colorama.init should somehow be more explicit, thus putting the responsibility for making sure it's activated only when needed on the shoulders of the caller. So, even though it wouldn't probably make sense to have something like colorama.patch(streams=[sys.stdout, sys.stderr]) but explicitly stating that colorama.init should be called if and only if sys.stdout/stderr in fact are the real stdout and stderr. I guess the principle of side-effects and composability not playing nicely together is fully applicable here.

Also, regarding `isatty`—it really is just a heuristic approach to avoiding unwanted wrapping. Composing with other wrappers is a good example of this. So perhaps this check should simply be eliminated in future versions of colorama and an explicit note added to the documentation about colorama.init not being meant to be called fully unconditionally.

Regardless of this though, the `orig_stdout` and `orig_stderr` globals should not be initialised prematurely as they are now and should instead be set to the current values of sys.stderr and sys.stdout at the time when colorama.init is called.

**Comment by tartley** [comment]
From Dave B:

On Windows, there are tons of problems with unicode output on Python
2.7, which I've heard are fixed in Python 3.0 (related to cp65001 not
mapping to utf-8 properly).  Anyway, to fix this, I have a bunch of
code that manually wraps the stdout/stderr to encode as utf-8 properly
at all times, no matter what the code page is.  However, colorama
overrides this with its own wrapper, due to the fact that the
orig_stdout/orig_stderr are saved as globals during IMPORT (colorama
global scope vars).

The fix is for Colorama to save these orig_xxx variables during
init().  This allows my own main to override stdout, and I can *then*
call colorama.init, which then wraps *my* stdout, and not the system's
original stdout.  This allows both the correctness of unicode, and the
colored goodness of colorama.

Dave.

**Comment by tartley** [comment]
from dbrackma
I think you should keep the isatty check, as it protects against trying to add color to stdout piped to a file, for example.  The above reference unicode wrapper has a bug where it always returns False for isatty.  The fix for that is to return False only if the UnicodeStream.hConsole is None, in which case it is not a true terminal.

**Comment by wiggin15** [comment]
Let's break it down:

> first of all, colorama needs to be activated after that wrapper because the other wrapper is more low level/fundamental

This is up to the caller.

> colorama remembers the orig_stdout and orig_stderr references in its initialise.py at import time, thus, by the time init() is called, any wrappings that have taken place before import colorama and init() are effectively cancelled/ignored

That's true. This has been reported in #32. I will fix this.

> colorama does not convert ANSI codes for streams who are not .isatty() == True; I'm not sure why such check was implemented in the first place, but it looks to me that colorama works perfectly well with streams that do not have such property.

Although it's true that colorama will not do anything when the stream is not a tty, the conversion to Win32 calls shouldn't happen in this case. Calling Win32 functions when there is redirections doesn't make sense. As dbrackma mentioned, the bug here is with the UnicodeStream wrapper (it shouldn't return isatty=False if outputting to the console), so I don't think we have something to fix here.

**Comment by wiggin15** [comment]
Fixed #32, I don't think there is more to do here.
