### ISSUE TITLE
py.test creates an environment that causes colorama to fail

### ISSUE THREAD

**Issue by tartley** [tartley/colorama#40]
Migrated from https://code.google.com/p/colorama/issues/detail?id=45
Reported by p.f.moore, Oct 3, 2013

When using py.test to run a file that imports colorama on Windows, the import fails (as far as I can tell, because the Windows standard handle does not point to a proper console)
Here's an example:
```
>type t.py
from pip.vendor import colorama
>python t.py >a
>type a
>py.test t.py
============================================= test session starts ============================================== platform win32 -- Python 3.3.0 -- pytest-2.4.1
collected 0 items / 1 errors

==================================================== ERRORS ==================================================== ____________________________________________ ERROR collecting t.py _____________________________________________ t.py:1: in <module>
>   from pip.vendor import colorama
pip\__init__.py:10: in <module>
>   from pip.log import logger
pip\log.py:11: in <module>
>   from pip.vendor import colorama
pip\vendor\colorama\__init__.py:1: in <module>
>   from .initialise import init, deinit, reinit
pip\vendor\colorama\initialise.py:4: in <module>
>   from .ansitowin32 import AnsiToWin32
pip\vendor\colorama\ansitowin32.py:11: in <module>
>       winterm = WinTerm()
pip\vendor\colorama\winterm.py:25: in __init__
>       self._default = win32.GetConsoleScreenBufferInfo(win32.STDOUT).wAttributes
pip\vendor\colorama\win32.py:64: in GetConsoleScreenBufferInfo
>           handle, byref(csbi))
E       ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_CONSOLE_SCREEN_BUFFER_INFO instance instead of pointer to CONSOLE_SCREEN_BUFFER_INFO
=========================================== 1 error in 0.74 seconds ===========================================
```
I'm not sure if this is a py.test bug or a colorama bug, so I have reported it to both projects. I suspect that maybe colorama should ensure on import that it does not try to initialise itself if the standard output is not suitable.

**Comment by tartley** [comment]
from tartley (me!):

It was my *intent* when I wrote Colorama that it should do nothing on import, until you call 'init', so I'm surprised that just importing colorama can cause a problem like this. I believe you though, so it looks like maybe I failed in that regard.

**Comment by tartley** [comment]
from p.f.moore:

Yes, this issue is still  present with 0.2.7.

A comment from the py.test developer: "pytest uses py.io.TerminalWriter() which implements coloring via ctypes call". I suspect that there's some nasty interaction between the two packages messing with the console somehow.

**Comment by tartley** [comment]
From geekademy@mgmiller.net:

:( I'm having the same problem.  I need to use ctypes and windll.kernel32.GetConsoleScreenBufferInfo(h, csbi) to get the terminal/console size for layout reasons.  But when using with colorama I get a kaboom instead.  I am going to try to reorder the calls, but it would be nice to know what the reason for this is and how to fix it.

I could have sworn this used to work.

**Comment by tartley** [comment]
from p.f.moore
See https://github.com/pyreadline/pyreadline/pull/24

The issue is that if you apply argtypes to something you're referencing as kernel32.XXX you get a shared copy. If your argtypes are too restrictive, this causes issues for other applications.

I don't know whether colorama needs a similar fix.

**Comment by tartley** [comment]
from  tartley
@p.f.moore. Thanks for the advice.

So the fix for colorama's incompatibility with pyreadline turned out to be to replace this:

    from ctypes import windll
    stdHandle = windll.kernel32.GetStdHandle
   
with this:

    import ctypes
    windll = LibraryLoader(ctypes.WinDLL)
    stdHandle = windll.kernel32.GetStdHandle

This apparently means I now have my own instance of windll, which can happily be incompatible with any other usage, and will cause no problems.

I'm at a loss as to whether that is expected to also fix this issue.

Can anyone else who has reported this issue still reproduce it against v0.3.0? I am not able to reproduce it.

Testing against significantly older versions is proving problematic since I lost the history when migrating to git because my Mercurial repo appeared to be corrupted (fresh checkouts could not display more than the first few entries of a log with diffs before giving 'no such node' errors after exiting.)

Does anyone know? Are there any other attributes of ctypes other than 'windll' which I should convert in a similar way? I'm going to go read the ctypes docs now, but when  I tried this the other night (tired), it didn't shed much light for me.

I'm likely to mark it as fixed unless anyone pipes up to contradict. Thanks for any input.

**Comment by pfmoore** [comment]
I'm OK with this being closed. It certainly isn't an issue any more (with current versions) and I'm happy to leave it at that.

**Comment by tartley** [comment]
Hooray, thanks for the update.
