### ISSUE TITLE
install colorama on python 2.7 on windows 8

### ISSUE THREAD

**Issue by tartley** [tartley/colorama#41]
Reported by rob.kelley06 @ googlecode
I am trying to install colorama on python 2.7 on windows 8

I am running the install command on administrator...

C:\Users\dianna\Desktop\outwar\colorama-0.3.3\setup.py install

i continue to get this error:

running install
running build
running build_py
error: package directory 'colorama' does not exist

any ideas?

**Comment by wiggin15** [comment]
Looks like this happens when not running setup.py from the colorama directory.
First
     
     cd C:\Users\dianna\Desktop\outwar\colorama-0.3.3\setup.py

and only then run

    python setup.py install

**Comment by wiggin15** [comment]
The docs say:

> You should always run the setup command from the distribution root directory, i.e. the top-level subdirectory that the module source distribution unpacks into.
