### ISSUE TITLE
support context manager syntax

### ISSUE THREAD

**Issue by tartley** [tartley/colorama#51]
Reported by steve at the domain 3xile dot com, Aug 8, 2011
It'd be nice to turn colorized output on and off with `with` rather than either init() or writing by hand, especially when other modules want to modify sys.stdout.  Here's an example implementation:

    import sys
    from colorama import Fore, AnsiToWin32

    class ConvertedOutput(object):
        def __init__(self, *AnsiToWin32Args, **kwargs):
            self._AnsiArgs = AnsiToWin32Args
            self._set_stderr = kwargs.get('stderr', None)
        def __enter__(self):
            self._stdout = sys.stdout
            sys.stdout   = AnsiToWin32(sys.stdout, *self._AnsiArgs)
            if self._set_stderr:
                sys.stderr = AnsiToWin32(sys.stderr, *self._AnsiArgs)
        def __exit__(self, type, value, traceback):
            sys.stdout = self._stdout

And example usage:

    with ConvertedOutput():
        print('%sThis text is red%s' % (Fore.RED, Fore.RESET))

    print('%sThis text is surrounded by junk%s' % (Fore.RED, Fore.RESET))

Migrated from https://code.google.com/p/colorama/issues/detail?id=28&can=1

**Comment by tartley** [comment]
Seems nice-to-have, but on the other hand, simple is good. Plus, I'm not sure of the use case when you want to have precise control over when conversion gets turned off, other than just program exit.

**Comment by stevenhoward** [comment]
It's been a few years now, but I believe in this case I was working with another library that also wanted to modify `sys.stdout`, and I ran into some issues that I've long forgotten.

**Comment by tartley** [comment]
I see. That makes sense then. Thanks Steven.

**Comment by wiggin15** [comment]
Fixed by #67.
