### ISSUE TITLE
Colorama causes pylint errors in client code

### ISSUE THREAD

**Issue by tartley** [tartley/colorama#54]
I don't know if this is an issue with colorama or with pylint.

What steps will reproduce the problem?
1. Use colorama in a project
2. Use predefined colors
3. Run pylint on the code

Result:
E:143,18: Instance of 'AnsiCodes' has no 'RED' member (no-member)
E:143,64: Instance of 'AnsiCodes' has no 'RESET' member (no-member)
E:157,47: Instance of 'AnsiCodes' has no 'BRIGHT' member (no-member)
E:158,45: Instance of 'AnsiCodes' has no 'RESET_ALL' member (no-member)
E:172,49: Instance of 'AnsiCodes' has no 'BRIGHT' member (no-member)
E:173,45: Instance of 'AnsiCodes' has no 'RESET_ALL' member (no-member)
E:187,49: Instance of 'AnsiCodes' has no 'BRIGHT' member (no-member)
E:188,45: Instance of 'AnsiCodes' has no 'RESET_ALL' member (no-member)

What is the expected output? What do you see instead?
Code passes the check

What version of the product are you using? On what operating system?
0.3.1 on Windows via Anaconda

Please provide any additional information below.
I found a similar issue with a patch on the Chromium project:
https://codereview.chromium.org/10202010

Reported by google code user peter.azp, Nov 12, 2014
Migrated from https://code.google.com/p/colorama/issues/detail?id=62

- - -

From Googlecode user nickjacobson:
The problem is that those attributes are dynamically set with setattr. See http://docs.pylint.org/plugins.html#example for description of this problem. To fix it, the colorama file ansi.py could be reworked to avoid use of setattr.

**Comment by tartley** [comment]
Presumably this only happens if a developer vendors a copy of colorama into their own source repo. If they just added a pinned version of colorama to their requirements, which was installed using pip (which I believe is best practice for the vast majority of cases) then this issue wouldn't be a problem. Tempted to mark 'wontfix'.

**Comment by autopulated** [comment]
This occurs even when using colorama via pip: because the attributes are set on the `AnsiCodes` object with `setattr`, pylint doesn't think they exist. 

What's irritating is that as far as I know there's no way to globally tell pylint to ignore attributes on the AnsiCodes type, so to suppress this (otherwise useful) error, I have to add `#pylint: disable=no-member` on every single line that accesses a colour code.

I think using `namedtuple` to create your AnsiCodes class would be one way to fix this, for example:
```python
Fore = namedtuple('AnsiCodes', ['RED', 'RESET', ....])(31, 39, ....)
```

**Comment by wiggin15** [comment]
I think namedtuples couldn't help in this case because we have to wrap the numbers with the escape sequences.
I committed a different fix. Thanks for raising this issue!
