### ISSUE TITLE
Color Style not reset after RESET when using LIGHT_EX colors in Windows

### ISSUE THREAD

**Issue by andyneff** [tartley/colorama#57]
When printing a Fore.LIGHT*_EX color and attempting to use Fore.RESET, in windows the colors stay "light" instead of returning to their normal state. A RESET_ALL or Style Change is needed to manually fix it.

In Linux, it behaves as expected.
![linux](https://cloud.githubusercontent.com/assets/7596961/7553202/d530ba42-f6b6-11e4-88c5-c631c89e7b06.png)

But in Windows 7, it does not
![windows](https://cloud.githubusercontent.com/assets/7596961/7553203/e107df8a-f6b6-11e4-821c-00ee6f90a992.png)
It's a little hard to see, but on the first line the d and e are bright, When only the d should be bright, and on the second line, the b, c, d, and e are all bright, when again, only the d should be bright.

**Comment by viswanathct** [comment]
Have stumbled across the same issue too. The following code isn't working as expected.
```python
import colorama
from colorama import Fore

Colors = [color for color in dir(Fore) if color[0] != '_']
Colors.remove('RESET')

colorama.init()

for color in sorted(Colors):
	print '%s%s%s' % (getattr(Fore, color), color, Fore.RESET)
	
print '-------------'

for color in Colors:
	print '%s%s%s' % (getattr(Fore, color), color, Fore.RESET)
```

The **BLACK** in the second list is printed in **LIGHTBLACK_EX**.

**Comment by andyneff** [comment]
I seem to have inadvertently created two discussions on here (#57 and #58 )
