### ISSUE TITLE
Win 7 64-bit Colorama installs but does not change color of output - newbie question?

### ISSUE THREAD

**Issue by bmoreinis** [tartley/colorama#60]
```
from colorama import init
init()
from colorama import Fore, Back, Style
print (Fore.RED + 'some red text')
```
Shows me blue text. 

Colorama is properly installed and updated using pip.   I am using the Python 3.4.3 Shell, running a file called testcolor.py. 

What am I missing?

**Comment by bmoreinis** [comment]
Yup, Noob problem.  IDE won't show text color changes.  Although PyCharm's IDE using console WILL do that - so that's the answer for folks insisting on using an IDE.

**Comment by MPagel** [comment]
No aspects of colorama work in windows command shell (cmd.exe) in 64-bit OSes beyond XP. So, it's not an IDE issue. The issue is that colorama functionality depends on ansi.sys being loaded, which is no longer default (or possible?) in cmd.exe

**Comment by wiggin15** [comment]
Hi @MPagel Would you care to elaborate? It sounds like you are reporting that colorama is generally not working on Windows cmd, but it is working fine on my environments (Windows 7, Windows 10 and Windows 2016 64-bit), and we had no other broad issues reported.

Can you specify your setup: which operating system, Python version and colorama version are you using?

Also, are you sure this is related to this issue? (what are you seeing? Is it blue text as well?)

In addition, I am not entirely sure what "ansi.sys" is (ansi.py does not import sys).

**Comment by skyem123** [comment]
`ansi.sys` is the name of a 16-bit MS-DOS driver that was probably included in 32-bit versions of Windows due to DOS compatibility.
It essentially works by emulating a terminal in DOS, interpreting the ANSI escape codes that applications write.

You could think of it (very loosely!) as a sort of genericn predecessor of colorama. From my understanding, colorama doesn't use it at all, and instead pokes the Win32 console bits based on what what applications read.

**Comment by MPagel** [comment]
my apologies. I thought I had thoroughly tested it, but until now neither colors nor navigation (e.g. \x1b[A) were working.  Now suddenly both work fine ;) So, I'll have to look into why e.g. https://github.com/tqdm/tqdm (see [PR363 ](https://github.com/tqdm/tqdm/pull/363) for my work-around) wasn't working for me earlier or if everything is magically okay now.
