### ISSUE TITLE
Use wheels.

### ISSUE THREAD

**Issue by SanketDG** [tartley/colorama#66]
I noticed that there is no wheels package on the pypi page even if there is a `setup.cfg`. Just `python setup.py bdist_wheel` and then uploading would do.

**Comment by wiggin15** [comment]
I added setup.cfg to support wheel distributions in future releases. I can't upload the latest release (v0.3.3) because its tag doesn't contain the file. I'm not sure if the current changes justify releasing a new version.

**Comment by SanketDG** [comment]
@wiggin15 Okay. I guess this issue can be closed after the release of the next version.

**Comment by srkunze** [comment]
I would like to see a wheel for colorama as well. :)

**Comment by graingert** [comment]
colorama is the highest ranking pure python library that doesn't support wheels

**Comment by graingert** [comment]
@tartley bump

**Comment by tartley** [comment]
Hey @graingert - I haven't used Windows for quite a few years now, so my contributions to Colorama are nonexistant these days. Others have picked up the reins though, and obviously if you'd find this feature useful, pull requests are always welcome. Big hugs!

**Comment by graingert** [comment]
@tartley the code is already there it just needs a deploy

**Comment by wiggin15** [comment]
Hi @graingert. I'm supposed to release a new version of colorama with a wheel distribution. I just opened a new issue that blocks the release, #80. Once we resolve it, I will upload a new version with a wheel.

**Comment by wiggin15** [comment]
I released a new version with a wheel distribution. I'm not sure if it registered as a universal wheel because the distribution is tagged with "Py Version: 2.7" and I don't know why. The name of the wheel file is ok... I tried to play with it a little, including passing "--universal" to the upload command trying more options against the pypi testing site. I can't find something I'm doing wrong so it must be something on PyPI's end.

**Comment by srkunze** [comment]
@wiggin15 According to http://pythonwheels.com/#pure-wheel that universal needs to be in a setup.cfg. Then, the name of the wheel should not include a python version.

**Comment by wiggin15** [comment]
Thanks for the link. The file setup.cfg is there, I just thought it didn't work when I saw the version on PyPI. The filename contains 'py2.py3' like other universal wheels. The wheel also installs correctly for Python 3. I'm pretty sure it's ok, just some glitch on PyPI.
