### ISSUE TITLE
Add dummy mode

### ISSUE THREAD

**Issue by opatut** [tartley/colorama#70]
I would like to make colour output configurable in my program, so I'd love to see a `dummy` parameter to `init()` that basically disables coloring, i.e. either strips all color codes from stdout/stderr or sets all color code variables to RESET.

**Comment by wiggin15** [comment]
I think passing strip=True, convert=False does that trick. Is this what you're looking for?

**Comment by wiggin15** [comment]
I'm closing this issue because this feature is available with the right flag combination.
