### ISSUE TITLE
TERM in the environment isn't a reliable check

### ISSUE THREAD

**Issue by mgedmin** [tartley/colorama#73]
1. Install Python and [Git for Windows](https://git-scm.com/downloads)
2. Launch Git Bash
3. Run `pip install anything`
4. Observe all kinds of ANSI escape sequences that should be stripped:
![ekrano nuotrauka is 2015-10-02 14-57-57](https://cloud.githubusercontent.com/assets/159967/10246381/62ae2ea2-6919-11e5-89da-24f6f2cbd166.png)

**Comment by mgedmin** [comment]
This is caused by `TERM` being set in the environment.
![ekrano nuotrauka is 2015-10-02 15-12-13](https://cloud.githubusercontent.com/assets/159967/10246387/7bc01234-6919-11e5-9634-2ae31ef470f1.png)

**Comment by mgedmin** [comment]
#35 seems to be related (but opposite to this one).

**Comment by wiggin15** [comment]
Hi. Thanks for reporting the issue. This looks like a duplicate of #48.
Can you please clone the current repository, run `python setup.py install`, and test if it's fixed?

**Comment by mgedmin** [comment]
My testcase is pip, which bundles its own vendored copy of all the dependencies.  I'm not quite sure how to force it to use a different version without breaking my Windows Jenkins machine.

It does look exactly like #48.  Apologies for not doing a search of closed bugs before filing a duplicate!
