### ISSUE TITLE
Consider no-tty handling, again

### ISSUE THREAD

**Issue by wiggin15** [tartley/colorama#80]
Following issue #47, reset codes are now emitted even when redirection is taking place (i.e., no tty).
Since colorama calls reset_all when the program terminates, there is now an undesired effect when using colorama and redirection -- a reset code will be emitted along with the redirected output. See:

    > python -c "import colorama; colorama.init(); print('a')" | xargs python -c "import sys; print(sys.argv)"
    ['-c', 'a', '\x1b[0m']

In other words, commands that take output from scripts with colorama will now get an extra ANSI reset code, which they probably don't expect.

* The bahavior before fixing #47: On Linux when there is no tty, reset_all codes were stripped but other ANSI codes were not stripped
* The current behavior: On Linux when there is no tty, nothing is stripped and both reset codes and other color codes are written to the redirected output
* New, suggested behavior: On Linux when there is no tty, all ANSI codes should be stripped

Note that on Windows when there is no tty, all ANSI codes are already stripped.
@tartley noted in #47 that colorama should behave like other unix utilities (like 'ls') and output color codes only on tty. I disagreed, but I changed my mind now.

The change in the code is simple, if I'm not mistaken: change the default `strip` value from:

   strip = conversion_supported

to 

    strip = conversion_supported or not is_a_tty(wrapped)

The impact is that the behavior of colorama on Linux with redirection will change.
Does this make sense? Does everyone agree that colorama should strip the color codes and the reset codes when there is no tty? Does the code change look right?
@tartley, your thoughts?

**Comment by tartley** [comment]
On first reading I agree with all of this. Will post more if further thoughts occur.

**Comment by wiggin15** [comment]
I'll commit this fix and release a new version during the weekend.

**Comment by davidhalter** [comment]
@wiggin15 I agree with this default behavior. Usually there are switches to turn colors back on (like pytest --color=yes). What do you think about adding such a switch to colorama? Some setting?

For some things I like piping colored output into `less -R` (which displays colors in less). However I agree that this should not be the default!
