### ISSUE TITLE
Excessive use causes crash

### ISSUE THREAD

**Issue by jcannell** [tartley/colorama#83]
Howdy,

Just started using colorama, noticed that when i use it in loops that print out colored text excessively, it crashes eventually. This is a shame, as I'm using it in a program that displays a colored menu (eventually the menu becomes sluggish and it eventually crashes)

Here is the beginning of the stacktrace:

`line 23, in green
    print color.Fore.LIGHTGREEN_EX + text
File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)
File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)
File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])
File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 36, in write
...
...
`
It's a never-ending loop of errors between lines 36, 137, 165, 170, 36, 137... and so on.

And here is the full green() func (where colorama is called color):

`
def green(text):
    color.init(autoreset=True)
    print color.Fore.LIGHTGREEN_EX + text
`

**Comment by jcannell** [comment]
Sorry that I'm stupid and don't know how to format that text properly :(

**Comment by takluyver** [comment]
To format a block of code, use triple backticks. Examples here: https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by wiggin15** [comment]
It's possible that you see this recursion because you're calling 'init' inside the function 'green' which you call in a loop. I think this causes re-wrapping the stream every time so that you get multiple calls to `write_and_convert`. Try calling `colorama.init` once at the beginning of your script, and see if this fixes your issue.

**Comment by jcannell** [comment]
I do call init, but with autoreset=True. This should deinit colorama after each use if I understand correctly. I need this functionality as I'm only coloring some letters on the line, not all of them. For example, my output is something like:

[c]onfig selection

where the "c" is the only letter colored. So far I haven't had much success at maintaining stable programs using colorama in this way, as I always get the recursion/crash eventually. It's a shame, really.

**Comment by wiggin15** [comment]
autoreset doesn't deinit colorama after each use. It just automatically sends "reset" codes after every "print". You shouldn't call 'colorama.init' more than once, and it's very likely that this is what's causing the issue.
To color only parts of the text you can use something like this:

    print colorama.Fore.RED + "c" + colorama.Fore.RESET + "onfig selection"

(and no need for autoreset)

**Comment by jcannell** [comment]
Thank you sir, just what I needed! Issue closed.
