### ISSUE TITLE
exception in ansitowin32.py, line 67 in Mac OS 10.11 Python 3.5 Anaconda 2.5 Spyder 2.3.8 

### ISSUE THREAD

**Issue by llevlion** [tartley/colorama#85]
AttributeError: 'SysOutput' object has no attribute 'closed'

I hit it when trying to bring up Preferences dialog in Spyder with Python 3.5: wrapped object might not have 'closed' attribute, so a check for it seems to be needed, like it is done in is_a_tty():

strip = conversion_supported or (hasattr(wrapped, 'closed') and not wrapped.closed and not is_a_tty(wrapped))

**Comment by wiggin15** [comment]
Hi. Thanks for reporting this. Can you please test the fix in this repository:
https://github.com/wiggin15/colorama/tree/issue84
(clone and checkout branch "issue84", then run: python setup.py install)
and let me know if it works for you?

**Comment by llevlion** [comment]
This works, but there is one more unguarded reference to wrapped.closed around line 148 in reset_all()

**Comment by wiggin15** [comment]
Thanks! I fixed the commit

**Comment by wiggin15** [comment]
Fixed in 1244a00
