### ISSUE TITLE
Question: Is it possible to convert back to ANSI codes from the win32 calls?

### ISSUE THREAD

**Issue by dougthor42** [tartley/colorama#88]
### Summary:
I'm wondering: Is it possible to convert from the win32 calls back to the ANSI color codes? Are the win32 calls even something that exists within the string?

(Note, I'm not asking about doing so within a single program: there's `deinit()` for that.)

Based on the discussion in the [Appveyor color issue](http://help.appveyor.com/discussions/suggestions/197-support-ansi-color-codes), I'm assuming that it's not possible. Is that correct?

> See the comments by Nathan Stocks (maintainer of [green](https://github.com/CleanCut/green)) - he had to turn **off** colorama so that ANSI codes would be sent to the server so that Appveyor could then convert them

### Reason for the Question:
I'm using a self-hosted [Gitlab](http://about.gitlab.com) instance and a [GitLab-CI Runner](https://about.gitlab.com/gitlab-ci/) running in a Windows environment, so I use Colorama to make the pretty colors happen. However, the web interface for GitLab is a unix terminal emulator. The CI runner pipes output to both STDOUT (Windows) and to this web interface (linux)  (at least that's how I believe it works - haven't confirmed yet).

What this means is that colors work locally (windows), but are not displayed correctly on the web UI ([GitLab Issue](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/332). I'm trying to help the GitLab guys out with fixing this issue, and one solution is to take any win32 calls and convert them back to ANSI on their end.

#### Windows CMD terminal:
![image](https://cloud.githubusercontent.com/assets/5386897/13360329/8d290b3a-dc6d-11e5-9c6a-2fc8d9b19aa6.png)

#### GitLab Web Interface
![image](https://cloud.githubusercontent.com/assets/5386897/13360298/59bf5e8e-dc6d-11e5-96b2-5f0d099b71c0.png)

**Comment by tartley** [comment]
FWIW, the win32 codes do not exist in the string that goes to stdout. They are calls made to functions in a Windows API.

To clarify your situation, does a single invocation of your code write to Windows stdout and to the gitlab web UI simultaneously, or is your code invoked on just one or the other?

**Comment by dougthor42** [comment]
> To clarify your situation, does a single invocation of your code write to Windows stdout and to the gitlab web UI simultaneously, or is your code invoked on just one or the other?

I'm pretty sure that it's invoked only on the windows machine and then written to both places simultaneously (or perhaps the webUI is a cached thing - only writing every X lines to save IO)

I'm working with the maintainer of `green` to get a `disable colorama` CLI option that I can add to my build script as a workaround. This will mean that the windows terminal will not be colored, but normally that is not shown - generally you only see the build cli via the web interface.

**Comment by tartley** [comment]
That sounds like the first of my two scenarios, so from my limited understanding it seems difficult to get everything to work perfectly.

> a disable colorama CLI option

Doesn't that mean that your windows terminal will not just be not-colored, but will also contain visible ansi character garbage? If you're going to have that, then you might as well just not use colorama at all, and it will produce the same results.

**Comment by dougthor42** [comment]
Yes, disabling colorama will have the ANSI garbage in the windows terminal. However, for the GitLab CI stuff, the windows terminal is never (well, rarely) seen - it's always piped to the emulated linux terminal on the webUI which interprets the ANSI codes.

> not use colorama at all,

Yup, that's basically what I'm adding to green: a "disable colorama" option for special cases such as these. We can't completely remove colorama from green because 1) colorama is awesome and 2) green needs to maintain windows support.

If I run green locally (Windows), then I simply don't include the "disable colorala" CLI argument and I get pretty colored output.

So in the end everything is happy and working, I just have to make sure to add an option to my CI yaml file.

Thanks for the feedback.
