### ISSUE TITLE
Output is not colored on Windows when redirecting standard output to a file

### ISSUE THREAD

**Issue by AndreLouisCaron** [tartley/colorama#95]
Hi there!

Thanks for this awesome project :-)

I've recently hit a case where I redirected the standard output to a file and all logs to standard error get these strange symbols:
```
←[33mWARNING←[0m:←[1mroot←[0m:←[33mApplied some throttling!←[0m
```

It seems like colorama doesn't detect that there is a tty when only the standard error stream is a tty.

I started digging through the code and noticed this:
```
# colorama/win32.py

def winapi_test():
    handle = handles[STDOUT]
    csbi = CONSOLE_SCREEN_BUFFER_INFO()
    success = _GetConsoleScreenBufferInfo(
        handle, byref(csbi))
    return bool(success)
```

If I change the code to this, then it works for me:
```
def _winapi_test(handle):
    csbi = CONSOLE_SCREEN_BUFFER_INFO()
    success = _GetConsoleScreenBufferInfo(
        handle, byref(csbi))
    return bool(success)

def winapi_test():
    return any(_winapi_test(h) for h in handles.values())
```

Any chance you're willing to accept a patch for this?

Thanks!

**Comment by wiggin15** [comment]
Hi. This looks good. If you open a pull request I'll merge it. Thanks!

**Comment by AndreLouisCaron** [comment]
Is there anything else I need to change (other than adding tests)?

**Comment by AndreLouisCaron** [comment]
@wiggin15 No pressure, but do you have an ETA on the next release that will include this fix?  Thanks!
