### ISSUE TITLE
Termcolor on Windows failing

### ISSUE THREAD

**Issue by al3xv3gas** [tartley/colorama#96]
When I execute 
<code>
form termcolor import colored
</code>
<code>
print (colored("Hello World!", "cyan"))
</code>
in the Python 2.7 and Python 3.5 shell on Windows, it doesn't work for me?

**Comment by wiggin15** [comment]
Hi. This is the Github repository for [colorama](https://pypi.python.org/pypi/colorama). [termcolor](https://pypi.python.org/pypi/termcolor) is a separate, unrelated package. As far as I know termcolor doesn't support Windows, but colorama does. Try to install colorama and convert your code to use it:

```python
import colorama
colorama.init()
print(colorama.Fore.CYAN + "Hello World!" + colorama.Fore.RESET)
```

**Comment by al3xv3gas** [comment]
Ok, thanks for telling me. One last question: What does the <code>'colorama.FORE.cyan' and 'colorama.Fore.RESET'</code> do?

**Comment by wiggin15** [comment]
The `colorama.Fore.*` and `colorama.Back.*` values are shortcuts to help generate ANSI sequences (see [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code)). For example:
```python
>>> colorama.Fore.CYAN
'\x1b[36m'
```
Unix terminals understand these special ANSI codes and will color text when you print them. On Windows, colorama catches these codes and converts them to Windows API calls. The [README](https://github.com/tartley/colorama/blob/master/README.rst) has some more information.

**Comment by al3xv3gas** [comment]
Ok thanks, I'll have a look.
