### ISSUE TITLE
Install procedure for Python 2.5?

### ISSUE THREAD

**Issue by al3xv3gas** [tartley/colorama#98]
How do I install Colorama on Python 2.5? And here's a suggestion. For questions like these, could you maybe make a Gitter Chatroom because it's kind of silly to open an issue for such a trivial question. Just saying!:)

**Comment by wiggin15** [comment]
Hi there!
colorama, like other Python packages, can be installed using [pip](https://pip.pypa.io/en/stable/installing/) (`pip install colorama`), easy_install from [setuptools](https://pypi.python.org/pypi/setuptools#installation-instructions) (`easy_install colorama`) or by cloning the repository and running [`python setup.py install`](https://docs.python.org/2/install/#the-new-standard-distutils)

**Comment by al3xv3gas** [comment]
Yes but Python 2.5 doesn't have the Pip package Manager..?

**Comment by kirbyfan64** [comment]
Does Python 2.5 have `easy_install`?

**Comment by wiggin15** [comment]
setuptools, which comes with `easy_install`, is available for Python 2.5. You can find the installation instructions [here](https://pypi.python.org/pypi/setuptools#installation-instructions).
The easiest method may be the last one I mentioned: clone this repository - or download the source distribution from pypi (https://pypi.python.org/pypi/colorama) and unzip it - and then in the colorama directory run: `python setup.py install`

**Comment by al3xv3gas** [comment]
Thank you! Issuer hereby closed!
